export const promptLanguages = [
  { name: "Українська", code: "UA", flag: "🇺🇦" },
  { name: "English", code: "GB", flag: "🇬🇧" },
  { name: "Deutsch", code: "DE", flag: "🇩🇪" },
  { name: "Français", code: "FR", flag: "🇫🇷" },
  { name: "Español", code: "ES", flag: "🇪🇸" },
  { name: "Italiano", code: "IT", flag: "🇮🇹" },
  { name: "Português", code: "PT", flag: "🇵🇹" },
  { name: "Polski", code: "PL", flag: "🇵🇱" },
  { name: "中文", code: "CN", flag: "🇨🇳" },
  { name: "日本語", code: "JP", flag: "🇯🇵" },
  { name: "한국어", code: "KR", flag: "🇰🇷" },
  { name: "العربية", code: "SA", flag: "🇸🇦" },
  { name: "Türkçe", code: "TR", flag: "🇹🇷" },
  { name: "Nederlands", code: "NL", flag: "🇳🇱" },
  { name: "Svenska", code: "SE", flag: "🇸🇪" },
  { name: "Norsk", code: "NO", flag: "🇳🇴" },
  { name: "Suomi", code: "FI", flag: "🇫🇮" },
  { name: "Ελληνικά", code: "GR", flag: "🇬🇷" },
  { name: "Čeština", code: "CZ", flag: "🇨🇿" },
  { name: "Magyar", code: "HU", flag: "🇭🇺" },
  { name: "Română", code: "RO", flag: "🇷🇴" },
  { name: "Български", code: "BG", flag: "🇧🇬" },
  { name: "Српски", code: "RS", flag: "🇷🇸" },
  { name: "Hrvatski", code: "HR", flag: "🇭🇷" },
  { name: "Slovenčina", code: "SK", flag: "🇸🇰" },
  { name: "Lietuvių", code: "LT", flag: "🇱🇹" },
  { name: "Latviešu", code: "LV", flag: "🇱🇻" },
  { name: "Eesti", code: "EE", flag: "🇪🇪" },
  { name: "Bahasa Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Tiếng Việt", code: "VN", flag: "🇻🇳" },
  { name: "हिन्दी", code: "IN", flag: "🇮🇳" },
  { name: "বাংলা", code: "BD", flag: "🇧🇩" },
  { name: "ไทย", code: "TH", flag: "🇹🇭" },
  { name: "فارسی", code: "IR", flag: "🇮🇷" },
  { name: "עברית", code: "IL", flag: "🇮🇱" },
  { name: "Bahasa Melayu", code: "MY", flag: "🇲🇾" },
];
